Convert personality txt files to yaml, and update app.py
openvinotoolkit/openvino_build_deploy pull request #144
Opened 2024-12-18 11:53 UTC by zhuo-yoyowz

Convert personality txt files to yaml, and update app.py

2024-12-19 10:26 UTC, adrianboguszewski requested changes
The extension change isn't enough for supporting yaml, because in code it still behaves as txt.
Please look at the virtual AI assistant, how yaml files are handled :)

2024-12-19 10:49 UTC, zhuo-yoyowz commented
Thanks for the comment! Updated the yaml file, according to the virtual AI assistant demo. Please help review again. Thanks!

2024-12-19 17:09 UTC, adrianboguszewski commented
It still won't work as expected. YAML files must be read through the yaml library. Once again, check the virtual AI assistant for loading and handling the content of the file.

2024-12-20 11:56 UTC, zhuo-yoyowz commented
Updated codes with YAML way to load the personality file. Please help review. Thank you!

2025-01-02 11:33 UTC, adrianboguszewski requested changes

2025-01-03 05:02 UTC, zhuo-yoyowz commented on ai_ref_kits/agentic_llm_rag/app.py
> +    react_system_prompt = PromptTemplate(chatbot_config['system_configuration'])
> Please check the correct usage of the PromptTemplate (https://docs.llamaindex.ai/en/stable/module_guides/models/prompts/). Passing anything from the yaml file here doesn't make sense. System configuration should be passed to OpenVINOLLM if I remember correctly.

Hi Adrian, according to the usage of passing "system prompt" to ReActAgent in LlamaIndex, it uses PromptTemplate and agent.update_prompts({"agent_worker:system_prompt": react_system_prompt}), as indicated here https://community.llamaindex.ai/how-do-i-give-a-reactagent-a-system-prompt-vKwmmFpb9xKb

2025-01-03 05:04 UTC, zhuo-yoyowz commented on ai_ref_kits/agentic_llm_rag/app.py
> +    react_system_prompt = PromptTemplate(chatbot_config['system_configuration'])
> And what about other sections from the yaml? What is the purpose of them if they are not used?

You're right. The UI for this agentic kit isn't designed to show greeting message and instructions on the interface, as what has been used in the virtual assistant demo. The rest of the sections are not used for now. What would you suggest? Shall I remove the rest sections? or Should I keep it, in case further UI designs may need to show these messages? Thanks!

2025-01-03 10:07 UTC, adrianboguszewski commented on ai_ref_kits/agentic_llm_rag/app.py
> +    react_system_prompt = PromptTemplate(chatbot_config['system_configuration'])
Ok, so the PromptTemplate class is misleading here.

I'm always a fan of the [KISS rule](https://en.wikipedia.org/wiki/KISS_principle), so I recommend removing anything, which isn't necessary. It can be easily restored later if needed :)

2025-01-07 13:53 UTC, merged