Merging Dev Branch Changes to Master
openvinotoolkit/openvino_build_deploy pull request #43
Opened 2024-08-26 16:35 UTC by riacheruvu

2024-08-27 11:18 UTC, adrianboguszewski commented
Thanks for this PR @riacheruvu 

Let's do the following:
1. Replace the PDF document with the Wiki page and provide the link to that in the main README file
2. Split this PR into 2, each containing just one demo and the related files

2024-08-27 11:19 UTC, adrianboguszewski reviewed
Thanks for this PR @riacheruvu

Let's do the following:

Replace the PDF document with the Wiki page and provide the link to that in the main README file
Split this PR into 2, each containing just one demo and the related files

2024-08-27 23:22 UTC, riacheruvu commented
Thank you, @adrianboguszewski! I've done so, and will create the second demo PR once this one is approved. I will be creating a separate PR for the README as it involves more restructuring.

2024-08-28 12:36 UTC, adrianboguszewski requested changes

2024-08-28 12:36 UTC, adrianboguszewski commented on demos/onnxruntime_yolov8_demo/requirements.txt
> +ultralytics==8.2.81
jupyterlab is missing here

2024-08-28 12:36 UTC, adrianboguszewski commented on demos/onnxruntime_yolov8_demo/YOLOv8 Object Detection with ONNX and OpenVINO Execution Provider.ipynb
> +    "!pip install ultralytics"
It's already installed in requirements

2024-08-28 12:36 UTC, adrianboguszewski commented on demos/onnxruntime_yolov8_demo/YOLOv8 Object Detection with ONNX and OpenVINO Execution Provider.ipynb
> +    "original_model_path = \"/content/model/yolov8m.onnx\"\n",
the model doesn't exists under this path

2024-08-29 12:17 UTC, adrianboguszewski requested changes
Ok. Everything works. So my only comment is to improve the README file. Please add there instructions on how to install/run it. A screenshot presenting demo would be also nice. We need something similar to: https://github.com/openvinotoolkit/openvino_build_deploy/blob/master/demos/onnxruntime_lcm_demo/README.md

2024-09-06 00:34 UTC, riacheruvu commented
> Ok. Everything works. So my only comment is to improve the README file. Please add there instructions on how to install/run it. A screenshot presenting demo would be also nice. We need something similar to: https://github.com/openvinotoolkit/openvino_build_deploy/blob/master/demos/onnxruntime_lcm_demo/README.md

Completed! @adrianboguszewski

2024-09-06 09:01 UTC, adrianboguszewski commented on demos/onnxruntime_yolov8_demo/README.md
> +- For details, please refer to [Installation Guide](../../README.md#-installation-guide).
```suggestion
```

2024-09-06 09:01 UTC, adrianboguszewski approved these changes

2024-09-06 09:02 UTC, merged