Adjustments to the README
openvinotoolkit/openvino_build_deploy pull request #44
Opened 2024-08-27 23:42 UTC by riacheruvu

Adding hyperlinks and additional descriptions to the README for the repository.

2024-08-27 23:43 UTC, riacheruvu commented
@adrianboguszewski @AnishaUdayakumar @raymondlo84 - would be great to get your feedback on the newly proposed README structure, if you have the time!

2024-08-28 11:25 UTC, adrianboguszewski requested changes

2024-08-28 11:25 UTC, adrianboguszewski commented on README.md
> +If you're looking for code samples or tutorials: You can find tutorial-based content at the [OpenVINO Notebooks]() repository, and hands-on Gen AI samples for Python and C++ at the OpenVINO.GenAI rep
No link to notebooks, no link to genai repo

2024-08-28 16:23 UTC, riacheruvu commented on README.md
> +|**[Adrian Boguszewski](https://www.linkedin.com/in/adrianboguszewski/)** <br> Deep Learning Expert <br> (Warsaw, Poland) <br><br> MSc in Computer Science <br> 5+ years as DL Engineer|**[Anisha Udaya
Ah sorry! Re-added :)

2024-08-29 10:10 UTC, adrianboguszewski approved these changes

2024-09-03 22:49 UTC, merged