Update Readme and app.py to replace SpeechT5 with MeloTTS for Conversational AI Assistant
openvinotoolkit/openvino_build_deploy pull request #92
Opened 2024-10-31 12:18 UTC by zhuo-yoyowz

2024-11-08 13:32 UTC, adrianboguszewski requested changes
And it doesn't work for me :( Ubuntu 24.04
```
Traceback (most recent call last):
  File "/home/abogusze/repos/openvino_build_deploy/ai_ref_kits/conversational_ai_chatbot/app.py", line 32, in <module>
    from melo.api import TTS
  File "/home/abogusze/repos/openvino_build_deploy/ai_ref_kits/conversational_ai_chatbot/venv/lib/python3.11/site-packages/melo/api.py", line 7, in <module>
    import torchaudio
  File "/home/abogusze/repos/openvino_build_deploy/ai_ref_kits/conversational_ai_chatbot/venv/lib/python3.11/site-packages/torchaudio/__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/abogusze/repos/openvino_build_deploy/ai_ref_kits/conversational_ai_chatbot/venv/lib/python3.11/site-packages/torchaudio/_extension/__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "/home/abogusze/repos/openvino_build_deploy/ai_ref_kits/conversational_ai_chatbot/venv/lib/python3.11/site-packages/torchaudio/_extension/utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "/home/abogusze/repos/openvino_build_deploy/ai_ref_kits/conversational_ai_chatbot/venv/lib/python3.11/site-packages/torch/_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /home/abogusze/repos/openvino_build_deploy/ai_ref_kits/conversational_ai_chatbot/venv/lib/python3.11/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK3c105Error4whatEv
```

2024-11-08 13:32 UTC, adrianboguszewski commented on ai_ref_kits/conversational_ai_chatbot/README.md
> +pip install "git+https://github.com/myshell-ai/MeloTTS.git"
This must be fixed on a specific commit

2024-11-08 13:32 UTC, adrianboguszewski commented on ai_ref_kits/conversational_ai_chatbot/app.py
> +    speaker_ids = model.hps.data.spk2id
do we need to assign it here? isn't it available in ` model.hps.data.spk2id` at any point?

2024-11-11 05:27 UTC, AnishaUdayakumar commented on ai_ref_kits/conversational_ai_chatbot/app.py
@zhuo-yoyowz  I successfully ran the App with the TTS model on my Windows AI PC after resolving issues with the torchaudio version and a few other dependencies.

To prevent similar issues, please ensure to provide compatible versions for the following crucial libraries:
- torch
- torchaudio
- transformers
- librosa
- melotts
- sentence-transformers

2024-11-20 08:14 UTC, closed without merging